import { Button } from '../ui/button'
import { 
  Sparkles, 
  Eye, 
  MessageSquare, 
  CheckCircle, 
  X, 
  FileText, 
  Download, 
  Copy,
  Users,
  TrendingUp
} from 'lucide-react'

const ResultsDisplay = ({ 
  ocrResults, 
  toolResults, 
  chatSessions, 
  currentMessage,
  setCurrentMessage,
  onClearOCR,
  onClearToolResults,
  onClearChat,
  onSendMessage
}) => {
  
  const generateSummaryReport = (toolResults) => {
    console.log('generateSummaryReport called with:', toolResults)
    console.log('toolResults.result:', toolResults.result)
    console.log('toolResults.result.result:', toolResults.result?.result)
    
    // Extract the actual summary data - it's nested in result.result
    const summaryData = toolResults.result?.result || toolResults.result
    console.log('summaryData:', summaryData)
    
    const summaryText = [
      'AI SUMMARY REPORT',
      '==================',
      '',
      'EXECUTIVE SUMMARY:',
      summaryData?.summary || 'No summary available',
      '',
      'KEY POINTS:',
      ...(summaryData?.keyPoints || []).map((point, i) => `${i + 1}. ${point}`),
      '',
      'SENTIMENT ANALYSIS:',
      `Positive: ${Math.round((summaryData?.sentiment?.positive || 0) * 100)}%`,
      `Neutral: ${Math.round((summaryData?.sentiment?.neutral || 0) * 100)}%`,
      `Negative: ${Math.round((summaryData?.sentiment?.negative || 0) * 100)}%`,
      '',
      'ENTITIES:',
      ...(summaryData?.entities || []).map(entity => `- ${entity}`),
      '',
      `Generated: ${new Date(toolResults.timestamp).toLocaleString()}`
    ].join('\n')

    const htmlContent = `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>AI Summary Report - RobotPDF</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%); color: #e2e8f0; min-height: 100vh; padding: 2rem; }
          .container { max-width: 800px; margin: 0 auto; background: rgba(30, 41, 59, 0.8); border-radius: 20px; padding: 2rem; box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5); backdrop-filter: blur(10px); border: 1px solid rgba(148, 163, 184, 0.1); }
          .header { text-align: center; margin-bottom: 2rem; padding-bottom: 1rem; border-bottom: 2px solid rgba(148, 163, 184, 0.2); }
          .header h1 { font-size: 2.5rem; font-weight: 800; background: linear-gradient(135deg, #a855f7 0%, #ec4899 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; margin-bottom: 0.5rem; }
          .section { margin-bottom: 2rem; background: rgba(15, 23, 42, 0.5); border-radius: 12px; padding: 1.5rem; border: 1px solid rgba(148, 163, 184, 0.1); }
          .summary-text { line-height: 1.7; color: #cbd5e1; background: rgba(15, 23, 42, 0.3); padding: 1rem; border-radius: 8px; border-left: 4px solid #a855f7; }
          .key-points { list-style: none; }
          .key-points li { background: rgba(15, 23, 42, 0.3); margin-bottom: 0.5rem; padding: 0.75rem; border-radius: 8px; border-left: 3px solid #3b82f6; }
          .entity-tag { background: linear-gradient(135deg, #a855f7 0%, #ec4899 100%); color: white; padding: 0.25rem 0.75rem; border-radius: 20px; font-size: 0.75rem; font-weight: 500; margin: 0.25rem; display: inline-block; }
          .btn { padding: 0.75rem 1.5rem; border: none; border-radius: 8px; font-weight: 600; cursor: pointer; margin: 0.5rem; }
          .btn-primary { background: linear-gradient(135deg, #a855f7 0%, #ec4899 100%); color: white; }
          .btn-secondary { background: rgba(148, 163, 184, 0.1); color: #e2e8f0; border: 1px solid rgba(148, 163, 184, 0.2); }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>AI Summary Report</h1>
            <p>Generated by RobotPDF Advanced AI</p>
          </div>
          
          <div class="section">
            <h2>Executive Summary</h2>
            <div class="summary-text">${(summaryData?.summary || 'No summary available').replace(/\n/g, '<br>')}</div>
          </div>
          
          ${summaryData?.keyPoints && summaryData.keyPoints.length > 0 ? `
          <div class="section">
            <h2>Key Points</h2>
            <ul class="key-points">
              ${summaryData.keyPoints.map((point, i) => `<li>${i + 1}. ${point}</li>`).join('')}
            </ul>
          </div>` : ''}
          
          ${summaryData?.sentiment ? `
          <div class="section">
            <h2>Sentiment Analysis</h2>
            <div>Positive: ${Math.round((summaryData.sentiment.positive || 0) * 100)}%</div>
            <div>Neutral: ${Math.round((summaryData.sentiment.neutral || 0) * 100)}%</div>
            <div>Negative: ${Math.round((summaryData.sentiment.negative || 0) * 100)}%</div>
          </div>` : ''}
          
          ${summaryData?.entities && summaryData.entities.length > 0 ? `
          <div class="section">
            <h2>Detected Entities</h2>
            <div>${summaryData.entities.map(entity => `<span class="entity-tag">${entity}</span>`).join('')}</div>
          </div>` : ''}
          
          <div style="text-align: center; margin-top: 2rem;">
            <button class="btn btn-primary" onclick="downloadReport()">📥 Download Report</button>
            <button class="btn btn-secondary" onclick="window.print()">🖨️ Print Report</button>
            <button class="btn btn-secondary" onclick="copyToClipboard()">📋 Copy Text</button>
          </div>
          
          <div style="text-align: center; margin-top: 2rem; color: #64748b; font-size: 0.875rem;">
            <p>Generated on ${new Date(toolResults.timestamp).toLocaleString()}</p>
            <p>Powered by RobotPDF AI • Professional PDF Tools</p>
          </div>
        </div>
        
        <script>
          const summaryText = ${JSON.stringify(summaryText)};
          
          function downloadReport() {
            try {
              const blob = new Blob([summaryText], { type: 'text/plain' });
              const url = URL.createObjectURL(blob);
              const a = document.createElement('a');
              a.href = url;
              a.download = 'ai_summary_${Date.now()}.txt';
              document.body.appendChild(a);
              a.click();
              document.body.removeChild(a);
              URL.revokeObjectURL(url);
            } catch (e) {
              alert('Download failed: ' + e.message);
            }
          }
          
          function copyToClipboard() {
            try {
              navigator.clipboard.writeText(summaryText).then(() => {
                alert('Summary copied to clipboard!');
              }).catch(() => {
                const textArea = document.createElement('textarea');
                textArea.value = summaryText;
                document.body.appendChild(textArea);
                textArea.select();
                document.execCommand('copy');
                document.body.removeChild(textArea);
                alert('Summary copied to clipboard!');
              });
            } catch (e) {
              alert('Copy failed: ' + e.message);
            }
          }
        </script>
      </body>
      </html>
    `

    try {
      const newWindow = window.open('', '_blank', 'width=900,height=700,scrollbars=yes,resizable=yes')
      if (newWindow) {
        newWindow.document.write(htmlContent)
        newWindow.document.close()
      } else {
        throw new Error('Popup blocked')
      }
    } catch (error) {
      const blob = new Blob([summaryText], { type: 'text/plain' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `ai_summary_${Date.now()}.txt`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    }
  }

  if (!ocrResults && !toolResults && Object.keys(chatSessions).length === 0) {
    return null
  }

  return (
    <div className="space-y-8 mb-8">
      {/* Smart Summary Results */}
      {toolResults && toolResults.type === 'smart-summary' && (
        <div className="bg-surface rounded-3xl border border-border p-8">
          <div className="flex items-center justify-between mb-6">
            <h3 className="text-xl font-semibold text-card-foreground flex items-center">
              <Sparkles className="h-5 w-5 mr-2" />
              AI Summary Complete
            </h3>
            <div className="flex items-center space-x-2">
              <div className="bg-green-600 text-white text-xs font-bold px-3 py-1 rounded-full">
                Ready
              </div>
              <Button
                onClick={onClearToolResults}
                size="sm"
                variant="outline"
                className="border-border text-card-foreground hover:bg-accent"
              >
                <X className="h-4 w-4" />
              </Button>
            </div>
          </div>
          
          <div className="text-center space-y-6">
            <div className="p-8 bg-elevated rounded-xl">
              <Sparkles className="h-16 w-16 text-yellow-400 mx-auto mb-4" />
              <h4 className="text-2xl font-bold text-card-foreground mb-2">
                AI Summary Generated Successfully!
              </h4>
              <p className="text-muted-foreground mb-6">
                Your document has been analyzed with AI insights, key points extraction, and sentiment analysis.
              </p>
              
              <Button
                onClick={() => generateSummaryReport(toolResults)}
                className="bg-gradient-to-r from-yellow-500 to-orange-600 text-white px-8 py-4 text-lg font-semibold hover:shadow-lg transition-all duration-300"
              >
                <FileText className="h-5 w-5 mr-2" />
                View Report
              </Button>
              
              <p className="text-xs text-secondary mt-4">
                Click to open your comprehensive AI summary report in a new window
              </p>
            </div>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* OCR Results */}
        {ocrResults && (
          <div className="bg-surface rounded-3xl border border-border p-8">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-xl font-semibold text-card-foreground flex items-center">
                <Eye className="h-5 w-5 mr-2" />
                OCR Results
              </h3>
              <div className="flex items-center space-x-2">
                <div className="bg-green-600 text-white text-xs font-bold px-3 py-1 rounded-full">
                  {Math.round(ocrResults.confidence || 0)}% confidence
                </div>
                <Button
                  onClick={onClearOCR}
                  size="sm"
                  variant="outline"
                  className="border-border text-card-foreground hover:bg-accent"
                >
                  <X className="h-4 w-4" />
                </Button>
              </div>
            </div>
            
            <div className="space-y-4">
              <div className="p-4 bg-elevated rounded-xl">
                <h4 className="font-medium text-card-foreground mb-2">{ocrResults.filename}</h4>
                <textarea
                  value={ocrResults.text}
                  readOnly
                  className="w-full bg-accent border border-border text-card-foreground rounded-lg p-3 h-32 resize-none"
                />
                <div className="flex justify-between items-center mt-3">
                  <span className="text-xs text-muted-foreground">
                    {ocrResults.pageCount || 0} pages • {ocrResults.detectedLanguage || 'Multiple languages'}
                  </span>
                  <Button
                    onClick={() => navigator.clipboard.writeText(ocrResults.text)}
                    size="sm"
                    variant="outline"
                    className="border-border text-card-foreground hover:bg-accent"
                  >
                    <Copy className="h-4 w-4 mr-1" />
                    Copy
                  </Button>
                </div>
              </div>
              
              {ocrResults.entities && ocrResults.entities.length > 0 && (
                <div className="p-4 bg-elevated rounded-xl">
                  <h4 className="font-medium text-card-foreground mb-2">Detected Entities</h4>
                  <div className="flex flex-wrap gap-2">
                    {ocrResults.entities.map((entity, index) => (
                      <span key={index} className="bg-blue-600 text-white text-xs px-2 py-1 rounded-full">
                        {entity}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        )}

        {/* AI Chat */}
        {Object.keys(chatSessions).length > 0 && (
          <div className="bg-surface rounded-3xl border border-border p-8">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-xl font-semibold text-card-foreground flex items-center">
                <MessageSquare className="h-5 w-5 mr-2" />
                AI Chat
              </h3>
              <Button
                onClick={onClearChat}
                size="sm"
                variant="outline"
                className="border-border text-card-foreground hover:bg-accent"
              >
                <X className="h-4 w-4 mr-1" />
                Close Chat
              </Button>
            </div>
            
            {Object.entries(chatSessions).map(([fileId, session]) => (
              <div key={fileId} className="space-y-4">
                <div className="flex items-center justify-between">
                  <h4 className="font-medium text-card-foreground">{session.filename}</h4>
                  <div className="bg-green-600 text-white text-xs font-bold px-3 py-1 rounded-full">
                    Active
                  </div>
                </div>
                
                <div className="h-48 overflow-y-auto bg-elevated rounded-xl p-4 space-y-3">
                  {session.messages.length === 0 ? (
                    <div className="text-center text-muted-foreground py-8">
                      <MessageSquare className="h-8 w-8 mx-auto mb-2 opacity-50" />
                      <p>Start a conversation with your document!</p>
                    </div>
                  ) : (
                    session.messages.map((message, index) => (
                      <div
                        key={index}
                        className={`flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}
                      >
                        <div
                          className={`max-w-xs px-4 py-2 rounded-xl ${
                            message.role === 'user'
                              ? 'bg-blue-600 text-white'
                              : 'bg-grey-700 text-grey-200'
                          }`}
                        >
                          <p className="text-sm">{message.content}</p>
                          {message.confidence && (
                            <p className="text-xs opacity-75 mt-1">
                              Confidence: {Math.round(message.confidence || 0)}%
                            </p>
                          )}
                        </div>
                      </div>
                    ))
                  )}
                </div>
                
                <div className="flex space-x-2">
                  <input
                    value={currentMessage}
                    onChange={(e) => setCurrentMessage(e.target.value)}
                    placeholder="Ask about this document..."
                    className="flex-1 bg-elevated border border-border text-card-foreground rounded-lg px-3 py-2"
                    onKeyPress={(e) => e.key === 'Enter' && onSendMessage(fileId)}
                  />
                  <Button
                    onClick={() => onSendMessage(fileId)}
                    className="bg-blue-600 hover:bg-blue-700"
                  >
                    <MessageSquare className="h-4 w-4" />
                  </Button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* AI Chat Results Display */}
      {toolResults && toolResults.type === 'ai-chat' && (
        <div className="bg-surface rounded-3xl border border-border p-8 mb-8">
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center">
              <MessageSquare className="h-6 w-6 text-pink-400 mr-3" />
              <h3 className="text-xl font-semibold text-card-foreground">AI Chat Initialized</h3>
            </div>
            <div className="bg-green-600 text-white text-xs font-bold px-3 py-1 rounded-full">
              Ready
            </div>
          </div>
          
          <div className="bg-elevated rounded-xl p-6 text-center">
            <MessageSquare className="h-12 w-12 text-pink-400 mx-auto mb-4" />
            <h4 className="text-lg font-semibold text-card-foreground mb-2">
              AI Chat is Ready!
            </h4>
            <p className="text-muted-foreground mb-4">
              Your document has been processed and is ready for AI-powered conversations.
              You can now ask questions about the content.
            </p>
            <Button className="bg-pink-600 hover:bg-pink-700 text-white">
              <MessageSquare className="h-4 w-4 mr-2" />
              Start Chatting
            </Button>
          </div>
        </div>
      )}

      {/* Tool Results Display */}
      {toolResults && !['smart-summary', 'ai-chat'].includes(toolResults.type) && (
        <div className="bg-surface rounded-3xl border border-border p-8 mb-8">
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center">
              <CheckCircle className="h-6 w-6 text-green-400 mr-3" />
              <h3 className="text-xl font-semibold text-card-foreground">Processing Complete</h3>
            </div>
            <div className="bg-green-600 text-white text-xs font-bold px-3 py-1 rounded-full">
              Success
            </div>
          </div>
          
          <div className="bg-elevated rounded-xl p-6">
            <div className="flex items-center justify-between">
              <div>
                <h4 className="text-lg font-semibold text-card-foreground mb-1">
                  {toolResults.toolName} Completed
                </h4>
                <p className="text-muted-foreground">
                  Your files have been processed successfully and downloaded.
                </p>
              </div>
              <div className="text-right">
                <div className="text-sm text-muted-foreground">
                  Processed at: {new Date(toolResults.timestamp).toLocaleString()}
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default ResultsDisplay