import {
  Eye,
  MessageSquare,
  Sparkles,
  GitMerge,
  Scissors,
  Archive,
  Lock,
  Award,
  Upload,
  Brain,
  FileText,
  Users,
  CheckCircle,
  TrendingUp,
  Zap,
  Shield,
  Download,
  FileSpreadsheet,
  FileType
} from 'lucide-react'

export const proTools = [
  {
    id: 'advanced-ocr',
    icon: Eye,
    title: 'Advanced OCR Pro',
    description: 'AI-powered text extraction with 99.9% accuracy and multi-language support',
    color: 'from-cyan-500 to-blue-700',
    bgColor: 'bg-cyan-50',
    borderColor: 'border-cyan-200',
    textColor: 'text-cyan-700',
    iconBg: 'bg-cyan-500',
    acceptedFiles: '.pdf,.jpg,.jpeg,.png',
    multipleFiles: false,
    minFiles: 1,
    category: 'AI-Powered',
    popularity: 98,
    processingTime: '< 60s',
    features: ['Multi-language OCR', 'AI enhancement', 'Entity extraction', 'Confidence scoring']
  },
  {
    id: 'ai-chat',
    icon: MessageSquare,
    title: 'AI Document Chat',
    description: 'Intelligent conversations with your PDFs and images using advanced AI',
    color: 'from-pink-500 to-purple-700',
    bgColor: 'bg-pink-50',
    borderColor: 'border-pink-200',
    textColor: 'text-pink-700',
    iconBg: 'bg-pink-500',
    acceptedFiles: '.pdf,.jpg,.jpeg,.png,.gif,.bmp,.webp,.tiff,.tif',
    multipleFiles: false,
    minFiles: 1,
    category: 'AI-Powered',
    popularity: 95,
    processingTime: '< 30s',
    features: ['GPT-4 powered', 'Context awareness', 'Smart summaries', 'Multi-turn conversations']
  },
  {
    id: 'smart-summary',
    icon: Sparkles,
    title: 'Smart Summary Pro',
    description: 'AI-generated summaries with key insights and sentiment analysis',
    color: 'from-yellow-500 to-orange-700',
    bgColor: 'bg-yellow-50',
    borderColor: 'border-yellow-200',
    textColor: 'text-yellow-700',
    iconBg: 'bg-yellow-500',
    acceptedFiles: '.pdf',
    multipleFiles: false,
    minFiles: 1,
    category: 'AI-Powered',
    popularity: 92,
    processingTime: '< 45s',
    features: ['Key insights', 'Sentiment analysis', 'Entity recognition', 'Executive summaries']
  },
  {
    id: 'pro-merge',
    icon: GitMerge,
    title: 'Pro Merge',
    description: 'Advanced PDF merging with bookmarks and professional options',
    color: 'from-blue-500 to-indigo-700',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-200',
    textColor: 'text-blue-700',
    iconBg: 'bg-blue-500',
    acceptedFiles: '.pdf',
    multipleFiles: true,
    minFiles: 2,
    category: 'Professional',
    popularity: 89,
    processingTime: '< 90s',
    features: ['Auto bookmarks', 'Page numbering', 'Title pages', 'Print optimization']
  },
  {
    id: 'precision-split',
    icon: Scissors,
    title: 'Precision Split',
    description: 'Advanced PDF splitting with custom ranges and batch processing',
    color: 'from-green-500 to-emerald-700',
    bgColor: 'bg-green-50',
    borderColor: 'border-green-200',
    textColor: 'text-green-700',
    iconBg: 'bg-green-500',
    acceptedFiles: '.pdf',
    multipleFiles: false,
    minFiles: 1,
    category: 'Professional',
    popularity: 87,
    processingTime: '< 75s',
    features: ['Custom ranges', 'Batch processing', 'Smart naming', 'Quality preservation']
  },
  {
    id: 'smart-compress',
    icon: Archive,
    title: 'Smart Compress Pro',
    description: 'Intelligent compression with quality control and optimization',
    color: 'from-purple-500 to-violet-700',
    bgColor: 'bg-purple-50',
    borderColor: 'border-purple-200',
    textColor: 'text-purple-700',
    iconBg: 'bg-purple-500',
    acceptedFiles: '.pdf',
    multipleFiles: true,
    minFiles: 1,
    category: 'Professional',
    popularity: 91,
    processingTime: '< 120s',
    features: ['Quality control', 'Image optimization', 'Size prediction', 'Batch processing']
  },
  {
    id: 'encrypt-pro',
    icon: Lock,
    title: 'Encrypt Pro',
    description: 'Military-grade encryption with advanced security features',
    color: 'from-red-500 to-pink-700',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-200',
    textColor: 'text-red-700',
    iconBg: 'bg-red-500',
    acceptedFiles: '.pdf',
    multipleFiles: true,
    minFiles: 1,
    category: 'Security',
    popularity: 85,
    processingTime: '< 60s',
    features: ['AES-256 encryption', 'Password protection', 'Digital signatures', 'Audit trails']
  },
  {
    id: 'images-to-pdf',
    icon: Upload,
    title: 'Images to PDF Pro',
    description: 'Convert multiple images to professional PDF with advanced settings',
    color: 'from-emerald-500 to-teal-700',
    bgColor: 'bg-emerald-50',
    borderColor: 'border-emerald-200',
    textColor: 'text-emerald-700',
    iconBg: 'bg-emerald-500',
    acceptedFiles: '.jpg,.jpeg,.png,.gif,.bmp,.webp',
    multipleFiles: true,
    minFiles: 1,
    category: 'Professional',
    popularity: 88,
    processingTime: '< 60s',
    features: ['Multiple formats', 'Custom page size', 'Quality control', 'Auto orientation']
  },
  {
    id: 'pdf-to-office',
    icon: FileSpreadsheet,
    title: 'PDF to Office Converter',
    description: 'Convert PDF to DOC, DOCX, Excel, PowerPoint with 100% accuracy',
    color: 'from-indigo-500 to-blue-700',
    bgColor: 'bg-indigo-50',
    borderColor: 'border-indigo-200',
    textColor: 'text-indigo-700',
    iconBg: 'bg-indigo-500',
    acceptedFiles: '.pdf',
    multipleFiles: true,
    minFiles: 1,
    category: 'Professional',
    popularity: 96,
    processingTime: '< 90s',
    features: ['Word conversion', 'Excel extraction', 'PowerPoint export', 'Format preservation']
  },
  {
    id: 'office-to-pdf',
    icon: FileType,
    title: 'Office to PDF Converter',
    description: 'Convert Word, Excel, PowerPoint to PDF with 100% accuracy',
    color: 'from-orange-500 to-red-700',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-200',
    textColor: 'text-orange-700',
    iconBg: 'bg-orange-500',
    acceptedFiles: '.doc,.docx,.xls,.xlsx,.ppt,.pptx,.rtf,.odt,.txt',
    multipleFiles: true,
    minFiles: 1,
    category: 'Professional',
    popularity: 96,
    processingTime: '< 90s',
    features: ['Word to PDF', 'Excel to PDF', 'PowerPoint to PDF', 'Format preservation']
  },
  {
    id: 'advanced-html-to-pdf',
    icon: FileText,
    title: 'Advanced HTML to PDF',
    description: 'Convert webpages or HTML files to PDF with custom settings',
    color: 'from-teal-500 to-cyan-700',
    bgColor: 'bg-teal-50',
    borderColor: 'border-teal-200',
    textColor: 'text-teal-700',
    iconBg: 'bg-teal-500',
    acceptedFiles: '.html,.htm',
    multipleFiles: false,
    minFiles: 0,
    category: 'Professional',
    popularity: 82,
    processingTime: '< 60s',
    requiresUrl: true,
    features: ['Full page capture', 'Custom page size', 'Header/Footer', 'Background graphics']
  }
]

export const PROCESSING_STEPS_CONFIG = {
  'advanced-ocr': [
    { name: 'Uploading File', icon: Upload },
    { name: 'AI Enhancement', icon: Brain },
    { name: 'Text Extraction', icon: Eye },
    { name: 'Entity Detection', icon: Users },
    { name: 'Complete', icon: CheckCircle }
  ],
  'ai-chat': [
    { name: 'Uploading File', icon: Upload },
    { name: 'Text Processing', icon: FileText },
    { name: 'Creating Embeddings', icon: Brain },
    { name: 'AI Initialization', icon: MessageSquare },
    { name: 'Complete', icon: CheckCircle }
  ],
  'smart-summary': [
    { name: 'Uploading File', icon: Upload },
    { name: 'Text Analysis', icon: Brain },
    { name: 'Generating Summary', icon: Sparkles },
    { name: 'Sentiment Analysis', icon: TrendingUp },
    { name: 'Entity Extraction', icon: Users },
    { name: 'Complete', icon: CheckCircle }
  ],
  'pro-merge': [
    { name: 'Uploading Files', icon: Upload },
    { name: 'Processing PDFs', icon: FileText },
    { name: 'Merging Documents', icon: GitMerge },
    { name: 'Optimizing Output', icon: Zap },
    { name: 'Complete', icon: CheckCircle }
  ],
  'precision-split': [
    { name: 'Uploading File', icon: Upload },
    { name: 'Analyzing Structure', icon: Eye },
    { name: 'Splitting Pages', icon: Scissors },
    { name: 'Creating Archive', icon: Archive },
    { name: 'Complete', icon: CheckCircle }
  ],
  'smart-compress': [
    { name: 'Uploading Files', icon: Upload },
    { name: 'Analyzing Content', icon: Eye },
    { name: 'Optimizing Images', icon: TrendingUp },
    { name: 'Compressing PDFs', icon: Archive },
    { name: 'Complete', icon: CheckCircle }
  ],
  'encrypt-pro': [
    { name: 'Uploading Files', icon: Upload },
    { name: 'Generating Keys', icon: Shield },
    { name: 'Applying Encryption', icon: Lock },
    { name: 'Security Verification', icon: CheckCircle },
    { name: 'Complete', icon: Download }
  ],
  'images-to-pdf': [
    { name: 'Uploading Images', icon: Upload },
    { name: 'Processing Images', icon: Eye },
    { name: 'Creating PDF', icon: FileText },
    { name: 'Optimizing', icon: Zap },
    { name: 'Complete', icon: CheckCircle }
  ],
  'pdf-to-office': [
    { name: 'Uploading PDF', icon: Upload },
    { name: 'Analyzing Structure', icon: Brain },
    { name: 'Extracting Content', icon: Eye },
    { name: 'Converting Format', icon: FileSpreadsheet },
    { name: 'Optimizing Output', icon: Zap },
    { name: 'Complete', icon: CheckCircle }
  ],
  'office-to-pdf': [
    { name: 'Uploading Files', icon: Upload },
    { name: 'Analyzing Content', icon: Brain },
    { name: 'Processing Document', icon: FileText },
    { name: 'Converting to PDF', icon: FileType },
    { name: 'Optimizing Output', icon: Zap },
    { name: 'Complete', icon: CheckCircle }
  ],
  'advanced-html-to-pdf': [
    { name: 'Fetching URL', icon: Upload },
    { name: 'Rendering Page', icon: Eye },
    { name: 'Applying Settings', icon: Zap },
    { name: 'Creating PDF', icon: FileText },
    { name: 'Complete', icon: CheckCircle }
  ]
}