/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './pages/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
    './app/**/*.{js,jsx}',
    './src/**/*.{js,jsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        sm: "2rem",
        lg: "4rem",
        xl: "5rem",
        "2xl": "6rem",
      },
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Dark Grey Color Palette
        grey: {
          50: "rgb(var(--grey-50))",
          100: "rgb(var(--grey-100))",
          200: "rgb(var(--grey-200))",
          300: "rgb(var(--grey-300))",
          400: "rgb(var(--grey-400))",
          500: "rgb(var(--grey-500))",
          600: "rgb(var(--grey-600))",
          700: "rgb(var(--grey-700))",
          800: "rgb(var(--grey-800))",
          900: "rgb(var(--grey-900))",
          950: "rgb(var(--grey-950))",
        },
        dark: {
          50: "rgb(var(--dark-50))",
          100: "rgb(var(--dark-100))",
          200: "rgb(var(--dark-200))",
          300: "rgb(var(--dark-300))",
          400: "rgb(var(--dark-400))",
          500: "rgb(var(--dark-500))",
          600: "rgb(var(--dark-600))",
          700: "rgb(var(--dark-700))",
          800: "rgb(var(--dark-800))",
          900: "rgb(var(--dark-900))",
        },
        // Accent Colors
        blue: {
          DEFAULT: "rgb(var(--accent-blue))",
          50: "rgb(239 246 255)",
          100: "rgb(219 234 254)",
          200: "rgb(191 219 254)",
          300: "rgb(147 197 253)",
          400: "rgb(96 165 250)",
          500: "rgb(var(--accent-blue))",
          600: "rgb(37 99 235)",
          700: "rgb(29 78 216)",
          800: "rgb(30 64 175)",
          900: "rgb(30 58 138)",
        },
        purple: {
          DEFAULT: "rgb(var(--accent-purple))",
          50: "rgb(250 245 255)",
          100: "rgb(243 232 255)",
          200: "rgb(233 213 255)",
          300: "rgb(196 181 253)",
          400: "rgb(167 139 250)",
          500: "rgb(var(--accent-purple))",
          600: "rgb(124 58 237)",
          700: "rgb(109 40 217)",
          800: "rgb(91 33 182)",
          900: "rgb(76 29 149)",
        },
        green: {
          DEFAULT: "rgb(var(--accent-green))",
          50: "rgb(240 253 244)",
          100: "rgb(220 252 231)",
          200: "rgb(187 247 208)",
          300: "rgb(134 239 172)",
          400: "rgb(74 222 128)",
          500: "rgb(var(--accent-green))",
          600: "rgb(22 163 74)",
          700: "rgb(21 128 61)",
          800: "rgb(22 101 52)",
          900: "rgb(20 83 45)",
        },
        orange: {
          DEFAULT: "rgb(var(--accent-orange))",
          50: "rgb(255 247 237)",
          100: "rgb(255 237 213)",
          200: "rgb(254 215 170)",
          300: "rgb(253 186 116)",
          400: "rgb(251 146 60)",
          500: "rgb(var(--accent-orange))",
          600: "rgb(234 88 12)",
          700: "rgb(194 65 12)",
          800: "rgb(154 52 18)",
          900: "rgb(124 45 18)",
        },
        red: {
          DEFAULT: "rgb(var(--accent-red))",
          50: "rgb(254 242 242)",
          100: "rgb(254 226 226)",
          200: "rgb(254 202 202)",
          300: "rgb(252 165 165)",
          400: "rgb(248 113 113)",
          500: "rgb(var(--accent-red))",
          600: "rgb(220 38 38)",
          700: "rgb(185 28 28)",
          800: "rgb(153 27 27)",
          900: "rgb(127 29 29)",
        },
        yellow: {
          DEFAULT: "rgb(var(--accent-yellow))",
          50: "rgb(254 252 232)",
          100: "rgb(254 249 195)",
          200: "rgb(254 240 138)",
          300: "rgb(253 224 71)",
          400: "rgb(250 204 21)",
          500: "rgb(var(--accent-yellow))",
          600: "rgb(202 138 4)",
          700: "rgb(161 98 7)",
          800: "rgb(133 77 14)",
          900: "rgb(113 63 18)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
        poppins: ['Poppins', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        slideUp: {
          from: { opacity: "0", transform: "translateY(30px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        slideDown: {
          from: { opacity: "0", transform: "translateY(-30px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        slideLeft: {
          from: { opacity: "0", transform: "translateX(30px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        slideRight: {
          from: { opacity: "0", transform: "translateX(-30px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        scaleIn: {
          from: { opacity: "0", transform: "scale(0.9)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        bounceIn: {
          "0%": { opacity: "0", transform: "scale(0.3)" },
          "50%": { opacity: "1", transform: "scale(1.05)" },
          "70%": { transform: "scale(0.9)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-20px)" },
        },
        pulseGlow: {
          "0%, 100%": { boxShadow: "0 0 20px rgba(82, 82, 91, 0.3)" },
          "50%": { boxShadow: "0 0 40px rgba(82, 82, 91, 0.6)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fadeIn 0.6s ease-out",
        "slide-up": "slideUp 0.6s ease-out",
        "slide-down": "slideDown 0.6s ease-out",
        "slide-left": "slideLeft 0.6s ease-out",
        "slide-right": "slideRight 0.6s ease-out",
        "scale-in": "scaleIn 0.6s ease-out",
        "bounce-in": "bounceIn 0.8s ease-out",
        "slide-up-fade": "slideUp 0.6s ease-out",
        "slide-down-fade": "slideDown 0.6s ease-out",
        "slide-left-fade": "slideLeft 0.6s ease-out",
        "slide-right-fade": "slideRight 0.6s ease-out",
        "scale-fade": "scaleIn 0.6s ease-out",
        "float": "float 6s ease-in-out infinite",
        "pulse-glow": "pulseGlow 2s ease-in-out infinite",
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'gradient-primary': 'var(--gradient-primary)',
        'gradient-secondary': 'var(--gradient-secondary)',
        'gradient-accent': 'var(--gradient-accent)',
        'gradient-surface': 'var(--gradient-surface)',
        'gradient-hero': 'var(--gradient-hero)',
        'gradient-blue': 'var(--gradient-blue)',
        'gradient-purple': 'var(--gradient-purple)',
        'gradient-green': 'var(--gradient-green)',
        'gradient-orange': 'var(--gradient-orange)',
        'gradient-red': 'var(--gradient-red)',
      },
      boxShadow: {
        'modern': 'var(--shadow)',
        'modern-md': 'var(--shadow-md)',
        'modern-lg': 'var(--shadow-lg)',
        'modern-xl': 'var(--shadow-xl)',
        'modern-2xl': 'var(--shadow-2xl)',
        'blue': 'var(--shadow-blue)',
        'blue-lg': 'var(--shadow-blue-lg)',
        'purple': 'var(--shadow-purple)',
        'green': 'var(--shadow-green)',
        'orange': 'var(--shadow-orange)',
        'red': 'var(--shadow-red)',
        'glass': 'var(--glass-shadow)',
      },
      backdropBlur: {
        xs: '2px',
        dark: '24px',
        'dark-sm': '12px',
        'dark-lg': '40px',
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
      },
      maxWidth: {
        '8xl': '88rem',
        '9xl': '96rem',
      },
      screens: {
        'xs': '475px',
      },
      borderWidth: {
        '3': '3px',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}